/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bogglegame;

import javax.swing.JOptionPane;

/**
 *
 * @author austi
 */
public class UIWindow extends javax.swing.JFrame {

    //The actual client, used as a middleman between UI and output
    private final Client parent;
    
    //array containing all the boggle game board buttons for easy access.
    private final javax.swing.JButton[] fullBoard;
    
    //used to deactivate buttons to prevent duplicate clicks.
    private int[] activeButtons = {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};
    
    //the array of positions that will be sent to server
    private int[] currentGuess = new int[0];
    
    //Checks if a boggle game is in progress. Switched to 1 when starts, back to 0 when ends.
    private int gameRunning = 0;
    
    //keeps track of the most recently clicked button, to avoid people deleting letters in the middle of words.
    private int lastClicked = -1;
    
    //keeps track of the player's score.
    private int score = 0;

    /**
     * Creates new form NewJFrame
     *
     * @param inClient
     */
    public UIWindow(Client inClient) {
        parent = inClient;
        initComponents();
        fullBoard = new javax.swing.JButton[16];
        fullBoard[0] = bBoard0;
        fullBoard[1] = bBoard1;
        fullBoard[2] = bBoard2;
        fullBoard[3] = bBoard3;
        fullBoard[4] = bBoard4;
        fullBoard[5] = bBoard5;
        fullBoard[6] = bBoard6;
        fullBoard[7] = bBoard7;
        fullBoard[8] = bBoard8;
        fullBoard[9] = bBoard9;
        fullBoard[10] = bBoard10;
        fullBoard[11] = bBoard11;
        fullBoard[12] = bBoard12;
        fullBoard[13] = bBoard13;
        fullBoard[14] = bBoard14;
        fullBoard[15] = bBoard15;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatWindow = new javax.swing.JTextArea();
        chatTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        guessedWordsWindow = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        guessWindow = new javax.swing.JTextArea();
        chatLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        guessedLabel = new javax.swing.JLabel();
        guessingLabel = new javax.swing.JLabel();
        sendGuessButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        bBoard0 = new javax.swing.JButton();
        bBoard1 = new javax.swing.JButton();
        bBoard2 = new javax.swing.JButton();
        bBoard3 = new javax.swing.JButton();
        bBoard4 = new javax.swing.JButton();
        bBoard5 = new javax.swing.JButton();
        bBoard6 = new javax.swing.JButton();
        bBoard7 = new javax.swing.JButton();
        bBoard8 = new javax.swing.JButton();
        bBoard9 = new javax.swing.JButton();
        bBoard10 = new javax.swing.JButton();
        bBoard11 = new javax.swing.JButton();
        bBoard12 = new javax.swing.JButton();
        bBoard13 = new javax.swing.JButton();
        bBoard14 = new javax.swing.JButton();
        bBoard15 = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        scoreNumber = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatWindow.setColumns(20);
        chatWindow.setRows(5);
        chatWindow.setEditable(false);
        jScrollPane2.setViewportView(chatWindow);

        chatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Send Chat");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        guessedWordsWindow.setColumns(20);
        guessedWordsWindow.setRows(5);
        guessedWordsWindow.setEditable(false);
        jScrollPane3.setViewportView(guessedWordsWindow);

        guessWindow.setColumns(20);
        guessWindow.setRows(5);
        guessWindow.setEditable(false);
        jScrollPane4.setViewportView(guessWindow);

        chatLabel.setText("Chat");

        gameLabel.setText("Boggle");

        guessedLabel.setText("Guessed Words");

        guessingLabel.setText("Your Guess");

        sendGuessButton.setText("Send Guess");
        sendGuessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendGuessButtonActionPerformed(evt);
            }
        });

        playButton.setText("PLAY");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        bBoard0.setFocusable(false);
        bBoard0.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard0.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard0.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard0ActionPerformed(evt);
            }
        });

        bBoard1.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard1.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard1.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard1ActionPerformed(evt);
            }
        });

        bBoard2.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard2.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard2.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard2ActionPerformed(evt);
            }
        });

        bBoard3.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard3.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard3.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard3ActionPerformed(evt);
            }
        });

        bBoard4.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard4.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard4.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard4ActionPerformed(evt);
            }
        });

        bBoard5.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard5.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard5.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard5ActionPerformed(evt);
            }
        });

        bBoard6.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard6.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard6.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard6ActionPerformed(evt);
            }
        });

        bBoard7.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard7.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard7.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard7ActionPerformed(evt);
            }
        });

        bBoard8.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard8.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard8.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard8ActionPerformed(evt);
            }
        });

        bBoard9.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard9.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard9.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard9ActionPerformed(evt);
            }
        });

        bBoard10.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard10.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard10.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard10ActionPerformed(evt);
            }
        });

        bBoard11.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard11.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard11.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard11ActionPerformed(evt);
            }
        });

        bBoard12.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard12.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard12.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard12ActionPerformed(evt);
            }
        });

        bBoard13.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard13.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard13.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard13ActionPerformed(evt);
            }
        });

        bBoard14.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard14.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard14.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard14ActionPerformed(evt);
            }
        });

        bBoard15.setMaximumSize(new java.awt.Dimension(80, 60));
        bBoard15.setMinimumSize(new java.awt.Dimension(80, 60));
        bBoard15.setPreferredSize(new java.awt.Dimension(80, 60));
        bBoard15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoard15ActionPerformed(evt);
            }
        });

        scoreLabel.setText("Score");

        scoreNumber.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBoard12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(bBoard13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(bBoard14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(bBoard15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bBoard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bBoard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bBoard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(bBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(scoreLabel)
                                            .addComponent(scoreNumber))))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(sendGuessButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(guessingLabel)
                                            .addComponent(guessedLabel))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameLabel)
                    .addComponent(guessedLabel)
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bBoard0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scoreNumber))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBoard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBoard12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBoard15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatLabel)
                    .addComponent(guessingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendGuessButton))
                    .addComponent(playButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTextFieldActionPerformed
        // Nothing, accidently made this when messing with window builder.
    }//GEN-LAST:event_chatTextFieldActionPerformed

    //The play button now sends a play message to the server
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        parent.sendPlay();        
        guessedWordsWindow.setText("");       
    }//GEN-LAST:event_playButtonActionPerformed

    //sends the currentGuess Array to the client to be checked and passed on, then clears the array.
    private void sendGuessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGuessButtonActionPerformed
        parent.sendGuess(currentGuess);
        currentGuess = new int[0];
        resetActiveButtons();
        updateGuessWord();
    }//GEN-LAST:event_sendGuessButtonActionPerformed

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        //Nothing, using ActionPerformed instead.
    }//GEN-LAST:event_playButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Nothing, accidently made this when messing with the window builder.
    }//GEN-LAST:event_jButton1ActionPerformed

    //the send chat button.
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        chatTextField.selectAll();
        String inputString = chatTextField.getSelectedText();
        parent.sendChat(inputString);
        chatTextField.setText(null);
    }//GEN-LAST:event_jButton1MouseClicked

    /*the following actions are for when buttons on the board are clicked.
    * Either clicks or unclicks buttons depending on when the buttons were clicked, if at all.
    */
    private void bBoard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard5ActionPerformed
        if (activeButtons[5] == 1) {
            boardClicked(5);
        } else if (lastClicked == 5) {
            boardUnclicked(5);
        }
    }//GEN-LAST:event_bBoard5ActionPerformed

    private void bBoard0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard0ActionPerformed
        if (activeButtons[0] == 1) {
            boardClicked(0);
        } else if (lastClicked == 0) {
            boardUnclicked(0);
        }

    }//GEN-LAST:event_bBoard0ActionPerformed

    private void bBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard1ActionPerformed
        if (activeButtons[1] == 1) {
            boardClicked(1);
        } else if (lastClicked == 1) {
            boardUnclicked(1);
        }
    }//GEN-LAST:event_bBoard1ActionPerformed

    private void bBoard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard2ActionPerformed
        if (activeButtons[2] == 1) {
            boardClicked(2);
        } else if (lastClicked == 2) {
            boardUnclicked(2);
        }
    }//GEN-LAST:event_bBoard2ActionPerformed

    private void bBoard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard3ActionPerformed
        if (activeButtons[3] == 1) {
            boardClicked(3);
        } else if (lastClicked == 3) {
            boardUnclicked(3);
        }
    }//GEN-LAST:event_bBoard3ActionPerformed

    private void bBoard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard4ActionPerformed
        if (activeButtons[4] == 1) {
            boardClicked(4);
        } else if (lastClicked == 4) {
            boardUnclicked(4);
        }
    }//GEN-LAST:event_bBoard4ActionPerformed

    private void bBoard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard6ActionPerformed
        if (activeButtons[6] == 1) {
            boardClicked(6);
        } else if (lastClicked == 6) {
            boardUnclicked(6);
        }
    }//GEN-LAST:event_bBoard6ActionPerformed

    private void bBoard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard7ActionPerformed
        if (activeButtons[7] == 1) {
            boardClicked(7);
        } else if (lastClicked == 7) {
            boardUnclicked(7);
        }
    }//GEN-LAST:event_bBoard7ActionPerformed

    private void bBoard8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard8ActionPerformed
        if (activeButtons[8] == 1) {
            boardClicked(8);
        } else if (lastClicked == 8) {
            boardUnclicked(8);
        }
    }//GEN-LAST:event_bBoard8ActionPerformed

    private void bBoard9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard9ActionPerformed
        if (activeButtons[9] == 1) {
            boardClicked(9);
        } else if (lastClicked == 9) {
            boardUnclicked(9);
        }
    }//GEN-LAST:event_bBoard9ActionPerformed

    private void bBoard10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard10ActionPerformed
        if (activeButtons[10] == 1) {
            boardClicked(10);
        } else if (lastClicked == 10) {
            boardUnclicked(10);
        }
    }//GEN-LAST:event_bBoard10ActionPerformed

    private void bBoard11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard11ActionPerformed
        if (activeButtons[11] == 1) {
            boardClicked(11);
        } else if (lastClicked == 11) {
            boardUnclicked(11);
        }
    }//GEN-LAST:event_bBoard11ActionPerformed

    private void bBoard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard12ActionPerformed
        if (activeButtons[12] == 1) {
            boardClicked(12);
        } else if (lastClicked == 12) {
            boardUnclicked(12);
        }
    }//GEN-LAST:event_bBoard12ActionPerformed

    private void bBoard13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard13ActionPerformed
        if (activeButtons[13] == 1) {
            boardClicked(13);
        } else if (lastClicked == 13) {
            boardUnclicked(13);
        }
    }//GEN-LAST:event_bBoard13ActionPerformed

    private void bBoard14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard14ActionPerformed
        if (activeButtons[14] == 1) {
            boardClicked(14);
        } else if (lastClicked == 14) {
            boardUnclicked(14);
        }
    }//GEN-LAST:event_bBoard14ActionPerformed

    private void bBoard15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoard15ActionPerformed
        if (activeButtons[15] == 1) {
            boardClicked(15);
        } else if (lastClicked == 15) {
            boardUnclicked(15);
        }
    }//GEN-LAST:event_bBoard15ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBoard0;
    private javax.swing.JButton bBoard1;
    private javax.swing.JButton bBoard10;
    private javax.swing.JButton bBoard11;
    private javax.swing.JButton bBoard12;
    private javax.swing.JButton bBoard13;
    private javax.swing.JButton bBoard14;
    private javax.swing.JButton bBoard15;
    private javax.swing.JButton bBoard2;
    private javax.swing.JButton bBoard3;
    private javax.swing.JButton bBoard4;
    private javax.swing.JButton bBoard5;
    private javax.swing.JButton bBoard6;
    private javax.swing.JButton bBoard7;
    private javax.swing.JButton bBoard8;
    private javax.swing.JButton bBoard9;
    private javax.swing.JLabel chatLabel;
    private javax.swing.JTextField chatTextField;
    private javax.swing.JTextArea chatWindow;
    private javax.swing.JLabel gameLabel;
    private javax.swing.JTextArea guessWindow;
    private javax.swing.JLabel guessedLabel;
    private javax.swing.JTextArea guessedWordsWindow;
    private javax.swing.JLabel guessingLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreNumber;
    private javax.swing.JButton sendGuessButton;
    // End of variables declaration//GEN-END:variables

    void couldNotConnect() {
        // TODO: Make new window saying "server can't be reached", close UI on close.
    }

    //ask user for username
    String getLogin() {
        String login = JOptionPane.showInputDialog("Please select a username:");
        return login;
    }

    //if username fails, asks the user to retry with a different username.
    String retryLogin() {
        String login = JOptionPane.showInputDialog("Username unavailable, please try again:");
        return login;
    }

    //adds strings onto the chat box.
    void updateChat(String username, String chatMessage) {
        chatWindow.append(username + ": " + chatMessage + "\n");
    }

    //Fills in characters onto the buttons for the boggle board.
    private void writeBoard(char[] charArray) {
        for (int i = 0; i < charArray.length; i++) {
            fullBoard[i].setText(Character.toString(charArray[i]));
            fullBoard[i].repaint();
        }
    }

    //used to unlock the board's buttons
    void startGame(char[] gameBoardArray) {
        gameRunning = 1;
        scoreNumber.setText("0");
        score = 0;
        writeBoard(gameBoardArray);
    }

    //used to lock the board's buttons
    void endGame() {
        gameRunning = 0;
    }

    //When a button is clicked, add the possition to the guess array
    private void boardClicked(int button) {
        if (gameRunning == 1) {
            int[] tempArray = new int[currentGuess.length + 1];
            System.arraycopy(currentGuess, 0, tempArray, 0, currentGuess.length);
            tempArray[tempArray.length - 1] = button;
            currentGuess = tempArray;
            lastClicked = button;
            activeButtons[button] = 0;
            updateGuessWord();
        }
    }

    //When a button is clicked after it's already been clicked, remove the letter from the word guess if that button was the last clicked.
    private void boardUnclicked(int button) {
        if (gameRunning == 1) {
            int[] tempArray = new int[currentGuess.length - 1];
            System.arraycopy(currentGuess, 0, tempArray, 0, tempArray.length);
            currentGuess = tempArray;
            try {
                lastClicked = currentGuess[currentGuess.length - 1];
            } catch (ArrayIndexOutOfBoundsException e) {
                lastClicked = -1;
                //this should catch the player removing the only item in the array.
            }
            activeButtons[button] = 1;
            updateGuessWord();
        }
    }

    //Creates and updates a string that has the current guess word.
    private void updateGuessWord() {
        String guessWord;
        char[] guessCharList = new char[currentGuess.length];
        for(int i = 0; i < guessCharList.length; i++){
            guessCharList[i] = fullBoard[currentGuess[i]].getText().charAt(0);
        }
        guessWord = new String(guessCharList);
        guessWindow.setText(guessWord);
    }

    //Adds words to the guessed window, signifying words that are no longer worth points.
    void markGuessed(String optString) {
        guessedWordsWindow.append(optString + "\n");
    }

    //Adds received points to the player's score.
    void updateScore(int optInt) {
        score += optInt;
        scoreNumber.setText(String.valueOf(score));
    }

    //upon sending a word, resets the buttons to be active again.
    private void resetActiveButtons() {
        for(int i = 0; i < activeButtons.length; i++){
            activeButtons[i] = 1;
        }
    }
}
